// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCrjxy68DClEV-rwXLhccvX8hO_-I68A',
    appId: '1:708130984645:web:2c1b5e6b49e531d61d96ac',
    messagingSenderId: '708130984645',
    projectId: 'zen-reminder-47164',
    authDomain: 'zen-reminder-47164.firebaseapp.com',
    storageBucket: 'zen-reminder-47164.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh9wgu6G6PRgbGUKsMJQ-VO6PfaOd4mRs',
    appId: '1:708130984645:android:59776e9ef75055111d96ac',
    messagingSenderId: '708130984645',
    projectId: 'zen-reminder-47164',
    storageBucket: 'zen-reminder-47164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPCEQorbTWhBOLQUTn8fkJl9CoOxMi6mI',
    appId: '1:708130984645:ios:c16d4d32dea3a31f1d96ac',
    messagingSenderId: '708130984645',
    projectId: 'zen-reminder-47164',
    storageBucket: 'zen-reminder-47164.appspot.com',
    iosBundleId: 'com.example.zenreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPCEQorbTWhBOLQUTn8fkJl9CoOxMi6mI',
    appId: '1:708130984645:ios:7159af51426e07931d96ac',
    messagingSenderId: '708130984645',
    projectId: 'zen-reminder-47164',
    storageBucket: 'zen-reminder-47164.appspot.com',
    iosBundleId: 'com.example.zenreminder.RunnerTests',
  );
}
